### ISSUE TITLE
Maybe do not list unpingable clients in fuse (or I/O-error the directory listings)

### ISSUE THREAD

**Issue by mrngm** [mrngm/rufs#12]

**Comment by dsprenkels** [comment]
Other options:

1. Warn the user by mangling the directory name `dsprenkels-UNREACHABLE`.
2. List directory contents, but use Linux permissions to list the files as unreadable.
3. Keep everything the same, but use Linux permissions to report only the user dir as unreadable.
4. Remove the user directory altogether from the root dir.

**Comment by dsprenkels** [comment]
This issue was moved to Jille/rufs#13
